BookingWeb.Server/Areas/Admin/Controllers/TaiKhoanAdminController.cs
using BookingWeb.Server.Controllers;
using BookingWeb.Server.Filters;
using BookingWeb.Server.Models;
using BookingWeb.Server.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookingWeb.Server.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Route("/Admin/[controller]")]
    [AuthorizeJWT]
    public class TaiKhoanAdminController : Controller
    {
        private readonly AccountService _accountService;

        public TaiKhoanAdminController(AccountService accountService)
        {
            _accountService = accountService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 8)
        {
            var viewModel = await _accountService.GetByPageAsync(pageNumber, pageSize);
            if (viewModel == null)
            {
                return BadRequest("Khong tim thay");
            }
            return View(viewModel);
        }

        [HttpPost("DeactivateAsync")]
        public async Task<IActionResult> DeactivateAsync(int id)
        {
            var result = await _accountService.DeactivateAsync(id);
            if (result)
            {
                TempData["AlertMessage"] = "Thay đổi trang thái thành công";
                TempData["AlertType"] = "success";
            }
            else
            {
                TempData["AlertMessage"] = "Deactivated failed";
                TempData["AlertType"] = "danger";
            }
            return RedirectToAction("Index");
        }
    }
}

BookingWeb.Server/Areas/Admin/Views/TaiKhoanAdmin/Index.cshtml
@model BookingWeb.Server.ViewModels.PagedList<BookingWeb.Server.ViewModels.TaiKhoanVM>

@{
ViewData["Title"] = "Phiếu đặt";
var currentDate = DateTime.Now.ToString("yyyy-MM-dd");
var startDateDefault = DateTime.Now.AddDays(-7).ToString("yyyy-MM-dd");
}
<h1 class="h3 mb-2 text-gray-800">Quản lý tài khoản</h1>
@Html.Partial("./../Shared/Alert.cshtml")

<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">   @*style="max-height: 400px; overflow-y: auto;"*@
            <table class="table table-bordered table-fixed" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>UserName</th>
                    <th>Trạng thái</th>
                    <th>Hành dộng</th>
                </tr>
                </thead>
                <tbody id="idTable" >
                @foreach (var tk in Model.Items)
                {
                    <tr>
                        <td >@tk.IdAccount</td>
                        <td >@tk.UserName</td>
                        <td>@(tk.TrangThai == true ? "Hoạt động" : "Đã khóa")</td>
                        <td>
                            <a href="@Url.Action("Detail", "TaiKhoanAdmin", new { id =@tk.IdAccount })" class="btn btn-info">Chi tiết</a>
                            @if (@tk.TrangThai == true)
                            {
                                <a type="submit" class="btn btn-danger" onclick="confirmDeactivate(@tk.IdAccount)">Khóa</a>
                            }
                            else if (@tk.TrangThai == false)
                            {
                                <a type="submit" class="btn btn-success" onclick="confirmDeactivate(@tk.IdAccount)">Mở khóa</a>
                            }
                        </td>
                    </tr>
                }
                </tbody>
            </table>
            <nav class="d-flex justify-content-between">
                <ul class="pagination">
                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                            <a class="page-link" href="@Url.Action("Index", new { pageNumber = i })">@i</a>
                        </li>
                    }
                </ul>
                <div>
                    <a class="btn btn-success" id="btnThemMoiTuyenDuong" data-bs-toggle="modal" data-bs-target="#addChuyenXe">Thêm mới</a>
                </div>
            </nav>
        </div>
    </div>
</div>

<script src="~/js/admin/taiKhoan.js"></script>