BookingWeb.Server/Areas/Admin/Controllers/PhieuDatAdminController.cs
using BookingWeb.Server.Filters;
using BookingWeb.Server.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookingWeb.Server.Areas.Admin.Controllers
{
    
    [Area("Admin")]
    [Route("/Admin/[controller]")]
    [AuthorizeJWT]
    public class PhieuDatAdminController : Controller
    {
        private readonly OrderService _orderService;
        
        public PhieuDatAdminController(OrderService orderService)
        {
            _orderService = orderService;
        }

        /*[HttpGet]
        public async Task<IActionResult> Index()
        {
            var viewModel = await _orderService.GetAllOrders();
            return View(viewModel);
        }*/
        
        [HttpGet]
        public async Task<IActionResult> Index(string startDate, string endDate)
        {
            if (string.IsNullOrEmpty(startDate))
            {
                startDate = DateTime.Now.AddDays(-7).ToString("yyyy-MM-dd");
            }
            
            if (string.IsNullOrEmpty(endDate))
            {
                endDate = DateTime.Now.ToString("yyyy-MM-dd");
            }
            
            var viewModel = await _orderService.GetByDate(startDate, endDate);
            return View(viewModel);
        }        
    }
}

BookingWeb.Server/Areas/Admin/Views/PhieuDatAdmin/Index.cshtml
@model List<BookingWeb.Server.ViewModels.OrderVM>

@{
ViewData["Title"] = "Phiếu đặt";
var currentDate = DateTime.Now.ToString("yyyy-MM-dd");
var startDateDefault = DateTime.Now.AddDays(-3).ToString("yyyy-MM-dd");
}

<style>
    .table-container {
        height: 550px;
        overflow: auto;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th {
        background: #fff;
        position: sticky;
        top: 0;
        z-index: 2;
        text-align: left;
        padding: 8px;
    }

    td {
        padding: 8px;
        border-bottom: 1px solid #eee;
    }
</style>

<h1 class="h3 mb-2 text-gray-800">Quản lý phiếu đặt</h1>
@Html.Partial("./../Shared/Alert.cshtml")

<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex justify-content-between align-items-center">
        <h6 class="m-0 font-weight-bold text-primary">Bảng dữ liệu</h6>
        <!-- Topbar Search -->
        <div class="input-group " style="width: 40%;">
            <form asp-action="Index" asp-controller="PhieuDatAdmin" method="get" class="d-flex w-100">
                <input type="date" name="startDate" class="form-control bg-light border-0 small me-2" value="@startDateDefault">
                <input type="date" name="endDate" class="form-control bg-light border-0 small me-2" value="@currentDate">
                <button class="btn btn-primary" type="submit">
                    <span class="material-symbols-outlined">
                        filter_alt
                    </span>
                </button>
            </form>
            <div class="ms-3 w-100">
                <a class="float-right mt-2" asp-action="Index" asp-controller="PhieuDatAdmin">Xem tất cả</a>
            </div>
        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive table-container">   @*style="max-height: 400px; overflow-y: auto;"*@
            <table class="table table-bordered table-fixed" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Thông tin người đặt</th>
                    <th>Ngày đặt</th>
                    <th>Tổng tiền</th>
                    <th>Trạng thái</th>
                </tr>
                </thead>
                <tbody id="idTable" >
                @foreach (var pd in Model)
                {
                    <tr>
                        <td >@pd.IdPhieu</td>
                        <td>@pd.IdUser</td>
                        <td>@pd.NgayLap</td>
                        <td>@pd.TongTien</td>
                        <td>@(pd.TrangThai == true ? "Đã thanh toán" : "Chưa thanh toán")</td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

@*<script src="~/js/admin/phieuDat.js"></script>*@